// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }

import Footer from "./Footer.jsx";

export const metadata = {
	title: 'Leander Christensen',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
		  <head>
		    <script src="https://kit.fontawesome.com/1e7874f6a9.js" crossOrigin="anonymous"></script>
		  </head>
		  <body>
		  	<div id="main">
		    	{children}
				<Footer />
			</div>
		  </body>
		</html>
	)
}